### ISSUE TITLE
WSMART team question

### ISSUE THREAD

**Issue by ghaglerepa** [Openscapes/2023-epa#10]
@aholder99 @abittnerepa @eischman Testing having something to resolve in WSMART.

Testing adding a task:

- [ ] Do this.

**Comment by ghaglerepa** [comment]
- [ ] Someone look for a VAMMS
- [ ] Send the VAMMS to someone.

**Comment by jhollist** [comment]
Testing tasks

- [ ] test
- [ ] test2

**Comment by stefaniebutland** [comment]
nice work folks. Thanks!
